name: Test

on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches:
      - main
    paths-ignore:
      - .github/workflows/Docs.yml
      - .github/workflows/Publish.yml
      - docs/README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/workflows/Docs.yml
      - .github/workflows/Publish.yml
      - docs/README.md

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Test
        shell: pwsh
        run: ./build.ps1 -Task Test -Bootstrap
